onEvent("recipes", (event) => {
    [
        {
            fluid: ["tconstruct:blazing_blood", BUCKET],
            input: { item: "create:blaze_burner" },
            temp: 32,
            time: 100,
            byproducts: [{ fluid: "tconstruct:molten_iron", amount: INGOT * 4 }],
        },
        {
            fluid: ["tconstruct:blood", INGOT],
            input: { item: "tconstruct:blaze_head" },
            temp: 1000,
            time: 400,
        },
        {
            fluid: ["tconstruct:blood", GEM],
            input: { item: "minecraft:cod" },
            temp: 32,
            time: 14,
        },
        {
            fluid: ["tconstruct:blood", mB * 40],
            input: { item: "farmersdelight:cod_slice" },
            temp: 32,
            time: 7,
        },
        {
            fluid: ["tconstruct:blood", GEM],
            input: { item: "minecraft:salmon" },
            temp: 32,
            time: 14,
        },
        {
            fluid: ["tconstruct:blood", mB * 40],
            input: { item: "farmersdelight:salmon_slice" },
            temp: 32,
            time: 7,
        },
        {
            fluid: ["tconstruct:blood", GEM],
            input: { item: "minecraft:tropical_fish" },
            temp: 32,
            time: 14,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET],
            input: { tag: "c:glass" },
            temp: 750,
            time: 59,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET],
            input: { item: "minecraft:glass_bottle" },
            temp: 750,
            time: 73,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET / 4],
            input: { tag: "c:glass_panes" },
            temp: 750,
            time: 29,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET / 4],
            input: { item: "tconstruct:blank_sand_cast" },
            temp: 750,
            time: 44,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET / 4],
            input: { item: "tconstruct:blank_red_sand_cast" },
            temp: 750,
            time: 44,
        },
        {
            fluid: ["tconstruct:molten_glass", BUCKET],
            input: { tag: "c:sand" },
            temp: 750,
            time: 88,
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET * 3],
            input: { item: "minecraft:beacon" },
            temp: 800,
            time: 345,
            byproducts: [{ fluid: "tconstruct:molten_glass", amount: BUCKET * 5 }],
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET],
            input: { tag: "c:obsidian" },
            temp: 800,
            time: 133,
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET * 8],
            input: { item: "minecraft:ender_chest" },
            temp: 800,
            time: 332,
            byproducts: [{ fluid: "tconstruct:molten_ender", amount: BUCKET / 4 }],
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET / 4],
            input: { tag: "c:dusts/obsidian" },
            temp: 800,
            time: 66,
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET],
            input: { item: "tconstruct:foundry_controller" },
            temp: 800,
            time: 232,
            byproducts: [{ fluid: "tconstruct:scorched_stone", amount: BUCKET }],
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET / 2],
            input: { item: "tconstruct:scorched_drain" },
            temp: 800,
            time: 166,
            byproducts: [{ fluid: "tconstruct:scorched_stone", amount: BUCKET }],
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET / 2],
            input: { item: "tconstruct:scorched_chute" },
            temp: 800,
            time: 166,
            byproducts: [{ fluid: "tconstruct:scorched_stone", amount: BUCKET }],
        },
        {
            fluid: ["tconstruct:molten_obsidian", BUCKET / 4],
            input: { item: "tconstruct:obsidian_pane" },
            temp: 800,
            time: 99,
        },
        {
            fluid: ["tconstruct:seared_stone", (BUCKET / 4) * 7], // prevents skips to get scorched stone due to seared casting basins being obtainable premoon
            input: { item: "tconstruct:scorched_basin" },
            temp: 500,
            time: 125,
        },
        {
            fluid: ["tconstruct:seared_stone", (BUCKET / 4) * 7], // prevents skips to get scorched stone due to seared casting tables being obtainable premoon
            input: { item: "tconstruct:scorched_basin" },
            temp: 500,
            time: 125,
        },
        {
            fluid: ["tconstruct:molten_bronze", INGOT / 2],
            input: { item: "createastral:bronze_sheet" },
            temp: 700,
            time: 57,
        },
        {
            fluid: ["kubejs:molten_calorite", BUCKET],
            input: { item: "ad_astra:calorite_block" },
            temp: 3000,
            time: 141,
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT],
            input: { item: "ad_astra:calorite_ingot" },
            temp: 3000,
            time: 47,
        },
        {
            fluid: ["kubejs:molten_calorite", NUGGET],
            input: { item: "ad_astra:calorite_nugget" },
            temp: 3000,
            time: 16,
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT * 13],
            input: { item: "ad_astra:raw_calorite_block" },
            temp: 3000,
            time: 283,
            byproducts: [{ fluid: "tconstruct:molten_diamond", amount: GEM_BLOCK / 9 }],
        },
        {
            fluid: ["kubejs:molten_calorite", NUGGET * 13],
            input: { tag: "c:raw_materials/calorite" },
            temp: 3000,
            time: 71,
            byproducts: [{ fluid: "tconstruct:molten_diamond", amount: GEM / 9 }],
        },
        {
            fluid: ["tconstruct:molten_copper", NUGGET],
            input: { tag: "c:wires/copper" },
            temp: 500,
            time: 10,
        },
        {
            fluid: ["kubejs:molten_desh", BUCKET],
            input: { item: "ad_astra:desh_block" },
            temp: 425,
            time: 141,
        },
        {
            fluid: ["kubejs:molten_desh", INGOT],
            input: { item: "ad_astra:desh_ingot" },
            temp: 425,
            time: 47,
        },
        {
            fluid: ["kubejs:molten_desh", NUGGET],
            input: { item: "ad_astra:desh_nugget" },
            temp: 425,
            time: 16,
        },
        {
            fluid: ["kubejs:molten_desh", INGOT * 13],
            input: { item: "ad_astra:raw_desh_block" },
            temp: 425,
            time: 283,
            byproducts: [{ fluid: "tconstruct:molten_iron", amount: (INGOT * 13) / 3 }],
        },
        {
            fluid: ["kubejs:molten_desh", NUGGET * 13],
            input: { tag: "c:raw_materials/desh" },
            temp: 425,
            time: 71,
            byproducts: [{ fluid: "tconstruct:molten_iron", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_iron", NUGGET],
            input: { item: "minecraft:chain" },
            temp: 800,
            time: 66,
        },
        {
            fluid: ["tconstruct:molten_iron", INGOT * 13],
            input: { tag: "c:storage_blocks/raw_iron" },
            temp: 790,
            time: 359,
            byproducts: [{ fluid: "tconstruct:molten_copper", amount: (INGOT * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_iron", (NUGGET * 13) / 3],
            input: { tag: "c:raw_materials/iron" },
            temp: 790,
            time: 90,
            byproducts: [{ fluid: "tconstruct:molten_copper", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_rose_gold", INGOT / 2],
            input: { item: "tconstruct:silky_cloth" },
            temp: 800,
            time: 66,
        },
        {
            fluid: ["tconstruct:molten_silver", INGOT * 2],
            input: { tag: "c:ores/silver" },
            temp: 225,
            time: 98,
            byproducts: [{ fluid: "kubejs:molten_desh", amount: INGOT * 2 }],
        },
        {
            fluid: ["tconstruct:molten_silver", INGOT * 13],
            input: { tag: "c:storage_blocks/raw_silver" },
            temp: 790,
            time: 359,
            byproducts: [{ fluid: "kubejs:molten_desh", amount: (INGOT * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_silver", NUGGET * 13],
            input: { tag: "c:raw_materials/silver" },
            temp: 790,
            time: 90,
            byproducts: [{ fluid: "kubejs:molten_desh", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_tin", NUGGET * 13],
            input: { tag: "c:ores/tin" },
            temp: 225,
            time: 98,
            byproducts: [{ fluid: "tconstruct:molten_copper", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_tin", INGOT * 13],
            input: { tag: "c:storage_blocks/raw_tin" },
            temp: 225,
            time: 234,
            byproducts: [{ fluid: "tconstruct:molten_copper", amount: (INGOT * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:molten_tin", NUGGET * 13],
            input: { tag: "c:raw_materials/tin" },
            temp: 790,
            time: 59,
            byproducts: [{ fluid: "tconstruct:molten_copper", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["kubejs:molten_ostrum", BUCKET],
            input: { item: "ad_astra:ostrum_block" },
            temp: 3000,
            time: 141,
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT],
            input: { item: "ad_astra:ostrum_ingot" },
            temp: 3000,
            time: 47,
        },
        {
            fluid: ["kubejs:molten_ostrum", NUGGET],
            input: { item: "ad_astra:ostrum_nugget" },
            temp: 3000,
            time: 16,
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT * 13],
            input: { item: "ad_astra:raw_ostrum_block" },
            temp: 3000,
            time: 283,
            byproducts: [{ fluid: "tconstruct:molten_lead", amount: (INGOT * 13) / 3 }],
        },
        {
            fluid: ["kubejs:molten_ostrum", NUGGET * 13],
            input: { tag: "c:raw_materials/ostrum" },
            temp: 3000,
            time: 71,
            byproducts: [{ fluid: "tconstruct:molten_lead", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["kubejs:molten_radiance", INGOT],
            input: { item: "create:refined_radiance" },
            temp: 425,
            time: 47,
        },
        {
            fluid: ["kubejs:molten_shadowsteel", INGOT],
            input: { item: "create:shadow_steel" },
            temp: 425,
            time: 200,
        },
        {
            fluid: ["kubejs:molten_yttrium", BUCKET],
            input: { item: "yttr:yttrium_block" },
            temp: 3000,
            time: 500,
        },
        {
            fluid: ["kubejs:molten_yttrium", INGOT],
            input: { item: "yttr:yttrium_ingot" },
            temp: 3000,
            time: 125,
        },
        {
            fluid: ["kubejs:molten_yttrium", NUGGET],
            input: { item: "yttr:yttrium_nugget" },
            temp: 3000,
            time: 32,
        },
        {
            fluid: ["kubejs:molten_yttrium", NUGGET * 13],
            input: { item: "yttr:yttrium_dust" },
            temp: 3000,
            time: 125,
            byproducts: [{ fluid: "kubejs:molten_calorite", amount: (NUGGET * 13) / 3 }],
        },
        {
            fluid: ["tconstruct:seared_stone", BUCKET / 4],
            input: { item: "tconstruct:grout" },
            temp: 600,
            time: 80,
        },
        {
            fluid: ["createaddition:seed_oil", BUCKET / 15],
            input: { item: "minecraft:beetroot" },
            temp: 100,
            time: 333,
        },
        {
            fluid: ["create:honey", BUCKET],
            input: { item: "minecraft:honey_block" },
            temp: 1,
            time: 98,
        },
    ].forEach((recipe) => {
        event.custom({
            type: "tconstruct:melting",
            ingredient: recipe.input,
            result: {
                fluid: recipe.fluid[0],
                amount: recipe.fluid[1],
            },
            temperature: recipe.temp,
            time: recipe.time,
            byproducts: recipe.byproducts ?? null,
        });
    });
});
