(function astralGeneratorsParticleAcceleratorRecipes() {
  onEvent("recipes", (event) => {
    acceleratorSingularity(event);
  });
  /** @param {Internal.RecipeEventJS} event  */
  function acceleratorSingularity(event) {
    event.custom({
      type: "custommachinery:custom_machine",
      machine: "astralgenerators:particle_accelerator",
      time: 10,
      requirements: [
        {
          type: "custommachinery:item",
          item: "minecraft:stone",
          amount: 1,
          mode: "input",
        },
        {
          type: "custommachinery:item",
          item: "minecraft:emerald",
          amount: 1,
          mode: "output",
        },
        {
          type: "custommachinery:fluid",
          mode: "input",
          fluid: "minecraft:water",
          amount: 100800,
        },
        {
          type: "custommachinery:energy",
          mode: "input",
          amount: 10000,
        },
        {
          type: "custommachinery:structure",
          keys: {
            a: "techreborn:basic_machine_frame",
            b: "techreborn:adjustable_su",
            c: "techreborn:adjustable_su",
            d: "astralgenerators:steel_frame",
            e: "astralgenerators:pipe_casing",
            f: "astralgenerators:vent",
            g: "astralgenerators:engine_intake_casing",
            h: "techreborn:advanced_machine_casing",
            i: "techreborn:fusion_coil",
            j: "astralgenerators:superconducting_coil",
          },
          pattern: [
            [
              "  aaaaaaaaaaaaa  ",
              " aaaaaaaaaaaaaaa ",
              "aaaaaaaaaaaaaaaaa",
              "aaaaaaaaaaaaaaaaa",
              "aaaaaabbbbbaaaaaa",
              "aaaaaaaaaaaaaaaaa",
              "aaaabaaaaaaabaaaa",
              "aaaabaaaaaaacaaaa",
              "aaaabaaaaaaabaaaa",
              "aaaabaaaaaaabaaaa",
              "aaaabaaaaaaabaaaa",
              "aaaaaaaaaaaaaaaaa",
              "aaaaaabbbbbaaaaaa",
              "aaaaaaaaaaaaaaaaa",
              "aaaaaaaaaaaaaaaaa",
              " aaaaaaaaaaaaaaa ",
              "  aaaaaamaaaaaa  ",
            ],
            [
              "                 ",
              "    d       d    ",
              "  dd         dd  ",
              "  d           d  ",
              " d             d ",
              "        e        ",
              "      fgfgf      ",
              "      g   g      ",
              "     ef   fe     ",
              "      g   g      ",
              "      fgfgf      ",
              "        e        ",
              " d             d ",
              "  d           d  ",
              "  dd         dd  ",
              "    d       d    ",
              "                 ",
            ],
            [
              "                 ",
              "    d       d    ",
              "  dd         dd  ",
              "  d           d  ",
              " d             d ",
              "        e        ",
              "      hhhhh      ",
              "      h   h      ",
              "     eh   he     ",
              "      h   h      ",
              "      hhhhh      ",
              "        e        ",
              " d             d ",
              "  d           d  ",
              "  dd         dd  ",
              "    d       d    ",
              "                 ",
            ],
            [
              "                 ",
              "    ddddddddd    ",
              "  ddddiiiiidddd  ",
              "  ddiiiiiiiiidd  ",
              " ddiiiiaaaiiiidd ",
              " ddiiaaaeaaaiidd ",
              " diiiahhhhhaiiid ",
              " diiaah   haaiid ",
              " diiaeh   heaiid ",
              " diiaah   haaiid ",
              " diiiahhhhhaiiid ",
              " ddiiaaaeaaaiidd ",
              " ddiiiiaaaiiiidd ",
              "  ddiiiiiiiiidd  ",
              "  ddddiiiiidddd  ",
              "    ddddddddd    ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "   d         d   ",
              "                 ",
              "        e        ",
              "      fghgf      ",
              "      g   g      ",
              "     eh   he     ",
              "      g   g      ",
              "      fghgf      ",
              "        e        ",
              "                 ",
              "   d         d   ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "   d         d   ",
              "                 ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "                 ",
              "   d         d   ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "   d         d   ",
              "                 ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "                 ",
              "   d         d   ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "   d         d   ",
              "                 ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "                 ",
              "   d         d   ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "   d         d   ",
              "                 ",
              "        e        ",
              "      fghgf      ",
              "      g   g      ",
              "     eh   he     ",
              "      g   g      ",
              "      fghgf      ",
              "        e        ",
              "                 ",
              "   d         d   ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "     ddddddd     ",
              "   dddiiiiiddd   ",
              "   diiiaaaiiid   ",
              "  ddiaaaeaaaidd  ",
              "  diiaaaaaaaiid  ",
              "  diaaa   aaaid  ",
              "  diaea   aeaid  ",
              "  diaaa   aaaid  ",
              "  diiaaaaaaaiid  ",
              "  ddiaaaeaaaidd  ",
              "   diiiaaaiiid   ",
              "   dddiiiiiddd   ",
              "     ddddddd     ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "                 ",
              "    d       d    ",
              "        e        ",
              "      fghgf      ",
              "      g   g      ",
              "     eh   he     ",
              "      g   g      ",
              "      fghgf      ",
              "        e        ",
              "    d       d    ",
              "                 ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "                 ",
              "    d       d    ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "    d       d    ",
              "                 ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "                 ",
              "    d       d    ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "    d       d    ",
              "                 ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "                 ",
              "    d       d    ",
              "        e        ",
              "      jjjjj      ",
              "      j   j      ",
              "     ej   je     ",
              "      j   j      ",
              "      jjjjj      ",
              "        e        ",
              "    d       d    ",
              "                 ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "                 ",
              "    d       d    ",
              "        e        ",
              "      fghgf      ",
              "      g   g      ",
              "     eh   he     ",
              "      g   g      ",
              "      fghgf      ",
              "        e        ",
              "    d       d    ",
              "                 ",
              "                 ",
              "                 ",
              "                 ",
            ],
            [
              "                 ",
              "                 ",
              "                 ",
              "      ddddd      ",
              "    dddiiiddd    ",
              "    diiieiiid    ",
              "   ddiaaaaaidd   ",
              "   diiafffaiid   ",
              "   dieafffaeid   ",
              "   diiafffaiid   ",
              "   ddiaaaaaidd   ",
              "    diiieiiid    ",
              "    dddiiiddd    ",
              "      ddddd      ",
              "                 ",
              "                 ",
              "                 ",
            ],
          ],
        },
      ],
    });
  }
})();
