name = "Create Astral"
author = "Laskyyy"
version = "test-release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcbc27b3158df32b8ca53a50e942fefbe950e04ed27cc815c536c11b994059d9"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
