name = "Create Astral"
author = "Laskyyy"
version = "2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68b929578a7008d6cb97529cc352c2003f62ab5934e90076ef0683c189408331"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
