name = "Create Astral"
author = "Laskyyy"
version = "2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6fd56b3819e20fefae67c40d458b29afecd0b9b6defac204bfd0fac375883a"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
