import { misc } from "./misc/misc";
import { planetDestroyer } from "./misc/planet_destroyer";
import { worldgen } from "./misc/worldgen";
import { createBlockModification } from "./modification/create/block";
import { createItemModification } from "./modification/create/item";
import { createAdditionItemModification } from "./modification/createaddition/item";
import { createAstralItemModification } from "./modification/createastral/item";
import { estrogenItemModification } from "./modification/estrogen/item";
import { farmersDelightItemModification } from "./modification/farmersdelight/item";
import { minecraftBlockModification } from "./modification/minecraft/block";
import { minecraftItemModification } from "./modification/minecraft/item";
import { techRebornBlockModification } from "./modification/techreborn/block";
import { techRebornItemModification } from "./modification/techreborn/item";
import { youreInGraveDangerBlockModification } from "./modification/yigd/block";
import { yttrBlockModification } from "./modification/yttr/block";
import { astralFoodsItemRegistry } from "./registry/astralfoods/item";
import { astralSignalsBlockRegistry } from "./registry/astralsignals/block";
import { astralSignalsItemRegistry } from "./registry/astralsignals/item";
import { createAstralBlockRegistry } from "./registry/createastral/block";
import { createAstralArmorTiersRegistry } from "./registry/createastral/item/armor_tiers";
import { createAstralItemRegistry } from "./registry/createastral/item/item";
import { createAstralToolTiersRegistry } from "./registry/createastral/item/tool_tiers";
import { definedsBlocksBlockRegistry } from "./registry/definedsblocks/block";
import { doodadsBlockRegistry } from "./registry/doodads/block";
import { kubeJSBlockRegistry } from "./registry/kubejs/block";
import { kubeJSFluidRegistry } from "./registry/kubejs/fluid";
import { kubeJSItemRegistry } from "./registry/kubejs/item";
import { yttrBlockRegistry } from "./registry/yttr/block";
import { adAstraTooltips } from "./tooltip/ad_astra";
import { adoptAFloppaTooltips } from "./tooltip/adoptafloppa";
import { ae2Tooltips } from "./tooltip/ae2";
import { astralAdditionsTooltips } from "./tooltip/astraladditions";
import { astralFoodsTooltips } from "./tooltip/astralfoods";
import { computerCraftTooltips } from "./tooltip/computercraft";
import { createTooltips } from "./tooltip/create";
import { createAstralTooltips } from "./tooltip/createastral";
import { createBigCannonsTooltips } from "./tooltip/createbigcannons";
import { extendedDrawersTooltips } from "./tooltip/extended_drawers";
import { extractinatorTooltips } from "./tooltip/extractinator";
import { kubeJSTooltips } from "./tooltip/kubejs";
import { minecraftTooltips } from "./tooltip/minecraft";
import { hephaestusTooltips } from "./tooltip/tconstruct";
import { techRebornTooltips } from "./tooltip/techreborn";
import { yttrTooltips } from "./tooltip/yttr";

const modpackVersion = "EXPERIMENTAL v2.1.4";

console.log(modpackVersion);

if (global.hasFired == undefined) global.hasFired = false;

if (!global.hasFired) {
  global.hasFired = true;
  misc();
  planetDestroyer();
  worldgen();
  createBlockModification();
  createItemModification();
  createAdditionItemModification();
  createAstralItemModification();
  estrogenItemModification();
  farmersDelightItemModification();
  minecraftBlockModification();
  minecraftItemModification();
  techRebornBlockModification();
  techRebornItemModification();
  youreInGraveDangerBlockModification();
  yttrBlockModification();
  
  astralFoodsItemRegistry();
  astralSignalsItemRegistry();
  astralSignalsBlockRegistry();
  createAstralArmorTiersRegistry();
  createAstralToolTiersRegistry();
  createAstralItemRegistry();
  createAstralBlockRegistry();
  definedsBlocksBlockRegistry();
  doodadsBlockRegistry();
  kubeJSBlockRegistry();
  kubeJSFluidRegistry();
  kubeJSItemRegistry();
  yttrBlockRegistry();

  adAstraTooltips();
  adoptAFloppaTooltips();
  ae2Tooltips();
  astralAdditionsTooltips();
  astralFoodsTooltips();
  computerCraftTooltips();
  createTooltips();
  createAstralTooltips();
  createBigCannonsTooltips();
  extendedDrawersTooltips();
  extractinatorTooltips();
  kubeJSTooltips();
  minecraftTooltips();
  hephaestusTooltips();
  techRebornTooltips();
  yttrTooltips();
}
