# Adapted from https://github.com/terrarium-earth/.github/

name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: [enhancement]
body:
    - type: textarea
      id: related-problem
      attributes:
          label: Is your feature request related to a problem?
          description: A clear and concise description of what the problem is.
          placeholder: I'm always frustrated when X happens.
      validations:
          required: false

    - type: textarea
      id: solution
      attributes:
          label: Solution(s)
          description: A clear and concise description of what you want to happen.
          placeholder: When X happens Y should happen like this other thing when A happens.
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: A clear and concise description of any alternative solutions or features you've considered.
          placeholder: Maybe X could also do Z when Y happens instead of X doing something when Y happens.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: You may also give any additional information here.
      validations:
          required: false
