import { hideFromREI } from "./scripts/hide_from_rei";
import { ponder } from "./scripts/ponder";
import { desizerPonder } from "./scripts/ponders/desizer";
import { sturdyCageDesizerPonder } from "./scripts/ponders/desizer_sturdy_cage";
import { ultrapureCarbonDesizerPonder } from "./scripts/ponders/desizer_ultrapure_carbon";
import { distilleryPonder } from "./scripts/ponders/distillation";
import { electrolyzerPonder } from "./scripts/ponders/electrolyzer";
import { moonPortalPonder } from "./scripts/ponders/moon_portal";
import { rootOfContinuityPonder } from "./scripts/ponders/root_of_continuity";
import { searedMelterPonder } from "./scripts/ponders/seared_melter";
import { shimmerRefineryPonder } from "./scripts/ponders/shimmer_refinery";
import { stoneGrowthChamberPonder } from "./scripts/ponders/stone_growth_chamber";
import { stoneGrowthChamberDummyPonder } from "./scripts/ponders/stone_growth_chamber_dummy";
import { rei } from "./scripts/rei";
import { stepUpFix } from "./scripts/step_up_fix";

hideFromREI();
rei();
ponder();
stepUpFix();
desizerPonder();
sturdyCageDesizerPonder();
ultrapureCarbonDesizerPonder();
distilleryPonder();
electrolyzerPonder();
moonPortalPonder();
rootOfContinuityPonder();
searedMelterPonder();
shimmerRefineryPonder();
stoneGrowthChamberDummyPonder();
stoneGrowthChamberPonder();