#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Dec 11 12:09:09 GMT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.1.1.zip
enableShaders=false
