onEvent("recipes", (event) => {
    [
        {
            fluid: ["kubejs:red_paste", 100 * mB],
            result: "minecraft:red_dye",
            cooling_time: 100,
        },
        {
            fluid: ["kubejs:shimmer", BUCKET / 20],
            result: "ae2:fluix_dust",
            cooling_time: 40,
            cast: [{ item: "ae2:certus_quartz_dust" }, true],
        },
        {
            fluid: ["tconstruct:molten_bronze", 4 * NUGGET],
            result: "create:cogwheel",
            cooling_time: 100,
            cast: [{ item: "tconstruct:coin_cast" }, false],
        },
        {
            fluid: ["tconstruct:molten_bronze", 12 * NUGGET],
            result: "create:large_cogwheel",
            cooling_time: 100,
            cast: [{ item: "tconstruct:gear_cast" }, false],
        },
        {
            fluid: ["tconstruct:molten_gold", 12 * NUGGET],
            result: "tconstruct:gear_cast",
            cooling_time: 100,
            cast: [{ item: "create:large_cogwheel" }, true],
        },
        {
            fluid: ["tconstruct:molten_gold", INGOT * 4],
            result: "createastral:golden_bowl",
            cooling_time: 100,
            cast: [{ item: "tconstruct:round_plate_cast" }, false],
        },
        {
            fluid: ["kubejs:liquid_xp_nuggies", INGOT],
            result: "createastral:experience_ingot",
            cooling_time: 100,
            cast: [{ item: "tconstruct:ingot_cast" }, false],
        },
        {
            fluid: ["kubejs:liquid_xp_nuggies", NUGGET],
            result: "create:experience_nugget",
            cooling_time: 10,
            cast: [{ item: "tconstruct:nugget_cast" }, false],
        },
        {
            fluid: ["kubejs:compound_mixture", mB * 11],
            result: "create:shaft",
            cooling_time: 10,
            cast: [{ item: "tconstruct:rod_cast" }, false],
        },
        {
            fluid: ["tconstruct:molten_uranium", mB * 500],
            result: "techreborn:data_storage_chip",
            cooling_time: 300,
            cast: [{ item: "tconstruct:rod_cast" }, false],
        },
        {
            fluid: ["kubejs:liquid_xp_nuggies", 8 * NUGGET],
            result: "minecraft:experience_bottle",
            cooling_time: 30,
            cast: [{ item: "minecraft:glass_bottle" }, true],
        },
        {
            fluid: ["tconstruct:molten_gold", INGOT],
            result: "createastral:gold_casted_rocket_fin",
            cooling_time: 30,
            cast: [{ item: "createastral:fragile_rocket_fin" }, true],
        },
        {
            fluid: ["tconstruct:molten_steel", INGOT],
            result: "astraladditions:steel_ring",
            cooling_time: 100,
            cast: [{ item: "astraladditions:ring_gold_cast" }, false],
        },
        {
            fluid: ["kubejs:shimmer", NUGGET * 3],
            result: "astraladditions:shimmer_lily",
            cooling_time: 20,
            cast: [{ item: "minecraft:lily_of_the_valley" }, true],
        },
        {
            fluid: ["tconstruct:seared_stone", NUGGET * 3],
            result: "astralfoods:seared_potato",
            cooling_time: 20,
            cast: [{ item: "minecraft:potato" }, true],
        },
        {
            fluid: ["kubejs:metabolic_broth", BUCKET / 4],
            result: "yttr:delicace",
            cooling_time: 50,
            cast: [{ item: "tconstruct:gem_cast" }, false],
        },
        {
            fluid: ["kubejs:molten_ostrum", NUGGET * 8],
            result: "createbigcannons:nethersteel_screw_lock",
            cooling_time: 60,
            cast: [{ item: "astraladditions:ring_gold_cast" }, false],
        },
        {
            fluid: ["kubejs:shimmer", INGOT / 2],
            result: "ae2:fluix_dust",
            cooling_time: 40,
            cast: [{ item: "minecraft:redstone" }, true],
        },
        {
            fluid: ["tconstruct:molten_steel", NUGGET * 8],
            result: "createbigcannons:steel_screw_lock",
            cooling_time: 60,
            cast: [{ item: "astraladditions:ring_gold_cast" }, false],
        },
        {
            fluid: ["kubejs:compound_mixture", INGOT],
            result: "create:andesite_alloy",
            cooling_time: 54,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["kubejs:compound_mixture", INGOT],
            result: "create:andesite_alloy",
            cooling_time: 54,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["tconstruct:molten_bronze", INGOT / 2],
            result: "createastral:bronze_sheet",
            cooling_time: 57,
            cast: [{ tag: "tconstruct:casts/multi_use/plate" }, false],
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT],
            result: "ad_astra:calorite_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT],
            result: "ad_astra:calorite_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["kubejs:molten_calorite", NUGGET],
            result: "ad_astra:calorite_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/multi_use/nugget" }, false],
        },
        {
            fluid: ["kubejs:molten_calorite", NUGGET],
            result: "ad_astra:calorite_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/single_use/nugget" }, true],
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT],
            result: "ad_astra:calorite_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/plate" }, false],
        },
        {
            fluid: ["kubejs:molten_calorite", INGOT],
            result: "ad_astra:calorite_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/plate" }, true],
        },
        {
            fluid: ["kubejs:molten_desh", INGOT],
            result: "ad_astra:desh_ingot",
            cooling_time: 47,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["kubejs:molten_desh", INGOT],
            result: "ad_astra:desh_ingot",
            cooling_time: 47,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["kubejs:molten_desh", NUGGET],
            result: "ad_astra:desh_nugget",
            cooling_time: 16,
            cast: [{ tag: "tconstruct:casts/multi_use/nugget" }, false],
        },
        {
            fluid: ["kubejs:molten_desh", NUGGET],
            result: "ad_astra:desh_nugget",
            cooling_time: 16,
            cast: [{ tag: "tconstruct:casts/single_use/nugget" }, true],
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT],
            result: "ad_astra:ostrum_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT],
            result: "ad_astra:ostrum_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["kubejs:molten_ostrum", NUGGET],
            result: "ad_astra:ostrum_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/multi_use/nugget" }, false],
        },
        {
            fluid: ["kubejs:molten_ostrum", NUGGET],
            result: "ad_astra:ostrum_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/single_use/nugget" }, true],
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT],
            result: "ad_astra:ostrum_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/plate" }, false],
        },
        {
            fluid: ["kubejs:molten_ostrum", INGOT],
            result: "ad_astra:ostrum_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/plate" }, true],
        },
        {
            fluid: ["kubejs:molten_radiance", INGOT],
            result: "create:refined_radiance",
            cooling_time: 200,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["kubejs:molten_radiance", INGOT],
            result: "create:refined_radiance",
            cooling_time: 200,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["kubejs:molten_shadowsteel", INGOT],
            result: "create:shadow_steel",
            cooling_time: 47,
            cast: [{ item: "ad_astra:steel_ingot" }, true],
        },
        {
            fluid: ["tconstruct:molten_steel", INGOT],
            result: "ad_astra:steel_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/ingot" }, false],
        },
        {
            fluid: ["tconstruct:molten_steel", INGOT],
            result: "ad_astra:steel_ingot",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/ingot" }, true],
        },
        {
            fluid: ["tconstruct:molten_steel", NUGGET],
            result: "ad_astra:steel_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/multi_use/nugget" }, false],
        },
        {
            fluid: ["tconstruct:molten_steel", NUGGET],
            result: "ad_astra:steel_nugget",
            cooling_time: 22,
            cast: [{ tag: "tconstruct:casts/single_use/nugget" }, true],
        },
        {
            fluid: ["tconstruct:molten_steel", INGOT],
            result: "ad_astra:steel_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/multi_use/plate" }, false],
        },
        {
            fluid: ["tconstruct:molten_steel", INGOT],
            result: "ad_astra:steel_plate",
            cooling_time: 65,
            cast: [{ tag: "tconstruct:casts/single_use/plate" }, true],
        },
        {
            fluid: ["tconstruct:magma", BUCKET / 8],
            result: "minecraft:brick",
            cooling_time: 45,
            cast: [{ item: "minecraft:flint" }, true],
        },
        {
            fluid: ["tconstruct:molten_clay", BUCKET / 8],
            result: "minecraft:brick",
            cooling_time: 51,
            cast: [{ item: "minecraft:stone_button" }, true],
        },
        {
            fluid: ["tconstruct:ichor", SLIMEBALL],
            result: "tconstruct:ichor_slime_ball",
            cooling_time: 46,
        },
    ].forEach((recipe) => {
        event.custom({
            type: "tconstruct:casting_table",
            cast: recipe.cast ? recipe.cast[0] : null,
            cast_consumed: recipe.cast ? recipe.cast[1] : false,
            fluid: {
                name: recipe.fluid[0],
                amount: recipe.fluid[1],
            },
            result: recipe.result,
            cooling_time: recipe.cooling_time,
        });
    });
});
