name: Create release branch

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: Version to display on all fields
        required: true

jobs:
  create-pullrequest:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: Astral-Experimental
          fetch-depth: 0

      - name: Get old version
        id: old-version
        shell: bash
        run: |
          echo "version=$(echo "$(<pack.toml)" | grep "version =" | cut -d '"' -f 2)" >> "$GITHUB_OUTPUT"

      - name: Download packwiz binary # now with static releases instead of action artifacts!
        id: download-packwiz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: The-Shortman/packwiz
          tag: "v1.0.0"
          fileName: Linux_x86-64.zip
          extract: true

      - name: Make packwiz binary executable
        shell: bash
        run: chmod +x ./packwiz

      # cant use sed easily here because it gets weird when the version grabber greps for regex characters like [] expecially in experimental versioning
      - name: Set pack.toml version
        id: packwiz-version
        shell: bash
        run: |
          while read -r line; do
            echo "${line//"${{steps.old-version.outputs.old_version}}"/"${{github.event.inputs.new_version}}"}"
          done < "pack.toml" > "tmp.toml"
          cat tmp.toml > pack.toml
          rm tmp.toml

      # need to set IFS to be empty so that read preserves whitespace
      - name: Set FancyMenu environment variable
        id: fancymenu-version
        shell: bash
        run: |
          OLD_IFS="$IFS"
          IFS=
          while read -r line; do
            echo "${line//"${{steps.old-version.outputs.old_version}}"/"${{github.event.inputs.new_version}}"}"
          done < "./config/fancymenu/user_variables.db" > "tmp.db"
          IFS="$OLD_IFS"
          cat tmp.db > ./config/fancymenu/user_variables.db
          rm tmp.db

      - name: Set startup debug log version
        id: startup-version
        shell: bash
        run: |
          OLD_IFS="$IFS"
          IFS=
          while read -r line; do
            echo "${line//"${{steps.old-version.outputs.old_version}}"/"${{github.event.inputs.new_version}}"}"
          done < "./kubejs/startup_scripts/misc/misc.js" > "tmp.js"
          IFS="$OLD_IFS"
          cat tmp.js > ./kubejs/startup_scripts/misc/misc.js
          rm tmp.js

      - name: Refresh packwiz
        id: refresh-packwiz
        shell: bash
        run: |
          ./packwiz refresh

      - name: Remove packwiz
        id: remove-packwiz
        shell: bash
        run: |
          rm ./packwiz

      - name: Create pull request to new release branch
        id: open-pr
        shell: bash
        run: |
          VERSION=${{github.event.inputs.new_version}}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "release/$VERSION"
          git add -A
          git commit -m "Prepare release"
          git push -u origin "release/$VERSION"
          gh pr create --title "Merge release/$VERSION into main" --body "Auto-generated by workflow. View changelog for more information at https://github.com/Laskyyy/Create-Astral/blob/release/$VERSION/CHANGELOG.md." --head "release/$VERSION" --base "main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
