name: Create release
run-name: "Release version ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to display on all fields (e.g. v2.1)
        required: true
        default: "v"
    paths:
      - "config"
      - "configureddefaults"
      - "defaultconfigs"
      - "fancymenustuff"
      - "journeymap"
      - "kubejs"
      - "mods"
      - "resourcepacks"
      - "schematics"
      - "serverpack"
      - "shaderpacks"
      - ".packwizignore"
      - "CHANGELOG.md"
      - "icon.png"
      - "index.toml"
      - "pack.toml"
      - "server.packwizignore"

jobs:
  get-info:
    name: Get modpack info
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.parse-changelog.outputs.description }}

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Parse changelog
        id: parse-changelog
        uses: coditory/changelog-parser@v1.0.2
        with:
          path: CHANGELOG.md
          version: ${{ inputs.version }}
        continue-on-error: true

  build-release:
    name: Build release artifacts
    runs-on: ubuntu-latest
    outputs:
      cf_name: ${{steps.construct-base-name.outputs.ASTRAL_CF_NAME}}.zip
      serverpack_name: ${{steps.construct-base-name.outputs.ASTRAL_SERVER_NAME}}.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Construct version strings
        id: construct-base-name
        shell: bash
        run: |
          VERSION=${{ inputs.version }}
          echo "ASTRAL_CF_NAME=Create-Astral-CurseForge-$VERSION" >> "$GITHUB_OUTPUT"
          echo "ASTRAL_SERVER_NAME=Create-Astral-Server-$VERSION" >> "$GITHUB_OUTPUT"
          FABRIC_VERSION_NUMBER="$(echo "$(<pack.toml)" | grep "fabric =" | cut -d '"' -f 2)"
          echo "FABRIC_VERSION=$FABRIC_VERSION_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Set in-game versions
        id: set-in-game-versions
        shell: bash
        run: |
          VERSION=${{ inputs.version }}

          sed -i -e "s/DEV/${VERSION}/g" pack.toml
          sed -i -e "s/DEV/${VERSION}/g" ./config/fancymenu/user_variables.db
          sed -i -e "s/DEV/${VERSION}/g" ./kubejs/startup_scripts/misc/misc.js

      - name: Download packwiz binary # now with static releases instead of action artifacts!
        id: download-packwiz
        uses: robinraju/release-downloader@v1.13
        with:
          repository: The-Shortman/packwiz
          tag: "v1.0.0"
          fileName: Linux_x86-64.zip
          extract: true

      - name: Make packwiz binary executable and refresh
        id: packwiz-refresh
        shell: bash
        run: |
          chmod +x ./packwiz
          ./packwiz refresh

      - name: Push changes to new tag
        id: create-tag
        shell: bash
        run: |
          VERSION=${{ inputs.version }}

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag $VERSION
          git push origin $VERSION

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"

      - name: Restore cached mod downloads
        id: cache-mods-restore
        uses: actions/cache/restore@v6
        with:
          path: /home/runner/.cache/packwiz/cache
          key: cached-mods
          restore-keys: |
            cached-mods-

      # servercore needs to be turned into a .toml for the curseforge export as CF won't accept it as an override jar
      - name: Prepare for CurseForge client zip creation
        shell: bash
        run: |
          mkdir temp-jar
          mv mods/servercore* ./temp-jar
          ./packwiz cf add https://www.curseforge.com/minecraft/mc-mods/servercore/files/4492100

      - name: Create CurseForge client zip
        shell: bash
        run: |
          ./packwiz curseforge export -o "${{steps.construct-base-name.outputs.ASTRAL_CF_NAME}}.zip"
          ./packwiz refresh

      - name: Clean up after CurseForge client zip creation
        shell: bash
        run: |
          ./packwiz remove servercore
          mv temp-jar/servercore* ./mods
          rm -r ./temp-jar

      - name: Prepare for serverpack creation
        run: |
          cat server.packwizignore >> .packwizignore
          mv serverpack/* ./
          ./packwiz refresh
          mkdir server

      - name: Download packwiz-installer-bootstrap
        uses: robinraju/release-downloader@v1.13
        with:
          repository: packwiz/packwiz-installer-bootstrap
          latest: true
          fileName: packwiz-installer-bootstrap.jar

      - name: Create serverpack
        run: |
          cd server
          java -jar ../packwiz-installer-bootstrap.jar -g -s server ../pack.toml
          curl "https://meta.fabricmc.net/v2/versions/loader/1.18.2/${{steps.construct-base-name.outputs.FABRIC_VERSION}}/0.11.1/server/jar" --output server.jar
          rm -f packwiz-installer.jar
          rm -f packwiz.json
          ls -l
          cd ../

      - name: Cache mod downloads
        id: cache-mods-save
        uses: actions/cache/save@v6
        with:
          path: |
            /home/runner/.cache/packwiz/cache
            ./server/mods
          key: cached-mods-${{ hashFiles('/home/runner/.cache/packwiz/cache/**/*') }}-${{ hashFiles('./server/mods') }}

      # Otherwise the artifact would be a zip in a zip, which can't be automatically installed in launchers
      - name: Unpack client pack for nicer artifact
        run: |
          unzip "${{steps.construct-base-name.outputs.ASTRAL_CF_NAME}}.zip" -d ./client

      - name: Upload client pack to GitHub
        uses: actions/upload-artifact@v7
        with:
          name: ${{steps.construct-base-name.outputs.ASTRAL_CF_NAME}}
          path: ./client

      - name: Upload serverpack to GitHub
        uses: actions/upload-artifact@v7
        with:
          name: ${{steps.construct-base-name.outputs.ASTRAL_SERVER_NAME}}
          path: ./server

  github-release:
    name: GitHub release
    needs: [get-info, build-release]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        id: checkout-tag
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.version }}
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          merge-multiple: true

      - name: Check if all artifacts are present
        id: check_artifacts
        shell: bash
        run: |
          if [ ! ${{ needs.build-release.outputs.cf_name }} ]; then
            echo '::error::No CurseForge pack found in artifacts.' && exit 1
          fi
          if [ ! ${{ needs.build-release.outputs.serverpack_name }} ]; then
            echo '::error::No server pack found in artifacts.' && exit 1
          fi

          echo "All artifacts found."

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v3.0.2
        with:
          name: ${{ inputs.version }}
          draft: true
          tag_name: ${{ inputs.version }}
          body: ${{ inputs.changelog }}
          files: |
            Create-Astral-CurseForge-${{ inputs.version }}.zip
            Create-Astral-Server-${{ inputs.version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  # automatic curseforge release coming soontm
